# Generated by Django 5.2.1 on 2026-05-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quote',
            name='symbol',
        ),
        migrations.RemoveIndex(
            model_name='assetcryptocoin',
            name='asset_crypt_symbol_072357_idx',
        ),
        migrations.RemoveField(
            model_name='assetcryptocoin',
            name='pair',
        ),
        migrations.RemoveField(
            model_name='assetcryptocoin',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='assetcryptocoin',
            name='volume',
        ),
        migrations.AddIndex(
            model_name='assetcryptocoin',
            index=models.Index(fields=['symbol'], name='assets_asse_symbol_fa6bee_idx'),
        ),
        migrations.AlterModelTable(
            name='assetcryptocoin',
            table=None,
        ),
        migrations.AlterModelTable(
            name='histquotes',
            table=None,
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
