# Generated by Django 5.2.7 on 2026-01-28 18:40

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AtrIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "intervals",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("1MIN", "1 minute"),
                                ("5MIN", "5 minutes"),
                                ("15MIN", "15 minutes"),
                                ("30MIN", "30 minutes"),
                                ("1HRS", "1 hour"),
                                ("1DAY", "1 day"),
                            ],
                            max_length=10,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("period", models.IntegerField(default=14)),
            ],
            options={
                "verbose_name": "ATR Indicator",
                "verbose_name_plural": "ATR Indicators",
            },
        ),
        migrations.CreateModel(
            name="BollingerBandsIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "intervals",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("1MIN", "1 minute"),
                                ("5MIN", "5 minutes"),
                                ("15MIN", "15 minutes"),
                                ("30MIN", "30 minutes"),
                                ("1HRS", "1 hour"),
                                ("1DAY", "1 day"),
                            ],
                            max_length=10,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("period", models.IntegerField(default=20)),
                ("std_dev", models.FloatField(default=2.0)),
            ],
            options={
                "verbose_name": "Bollinger Bands Indicator",
                "verbose_name_plural": "Bollinger Bands Indicators",
            },
        ),
        migrations.CreateModel(
            name="FnGValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.PositiveSmallIntegerField(default=0)),
                ("classification", models.CharField(max_length=100)),
                ("timestamp", models.PositiveBigIntegerField(default=0)),
                ("time_until_update", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Fear and Greed Value",
                "verbose_name_plural": "Fear and Greed Values",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AtrValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.DecimalField(decimal_places=10, max_digits=20)),
                (
                    "indicator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atr_values",
                        to="bots.atrindicator",
                    ),
                ),
                (
                    "quote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="assets.histquotes"
                    ),
                ),
            ],
            options={
                "verbose_name": "ATR Value",
                "verbose_name_plural": "ATR Values",
                "ordering": ["quote__time"],
            },
        ),
        migrations.CreateModel(
            name="BollingerBandsValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("upper_band", models.DecimalField(decimal_places=10, max_digits=20)),
                ("lower_band", models.DecimalField(decimal_places=10, max_digits=20)),
                ("middle_band", models.DecimalField(decimal_places=10, max_digits=20)),
                (
                    "indicator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bollinger_bands_values",
                        to="bots.bollingerbandsindicator",
                    ),
                ),
                (
                    "quote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="assets.histquotes"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bollinger Bands Value",
                "verbose_name_plural": "Bollinger Bands Values",
                "ordering": ["quote__time"],
            },
        ),
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published", models.BooleanField(default=False)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("roi", models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ("pnl", models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ("accuracy", models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ("frequency", models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ("risk", models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("max_drawdown", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("runtime", models.BigIntegerField(default=0)),
                ("last_activated", models.DateTimeField(blank=True, null=True)),
                ("intersection", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "bot_assets",
                    models.ManyToManyField(
                        blank=True, related_name="bots", to="assets.assetcryptocoin"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bots_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="bots_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bot",
            },
        ),
        migrations.AddField(
            model_name="bollingerbandsindicator",
            name="bot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bollinger_bands_indicators",
                to="bots.bot",
            ),
        ),
        migrations.AddField(
            model_name="atrindicator",
            name="bot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="atr_indicators",
                to="bots.bot",
            ),
        ),
        migrations.CreateModel(
            name="BotBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "initial_balance",
                    models.DecimalField(decimal_places=10, default=0, max_digits=20),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=10, default=0, max_digits=20),
                ),
                ("take_profit", models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ("stop_loss", models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                (
                    "unrealised_pnl",
                    models.DecimalField(decimal_places=10, default=0, max_digits=20),
                ),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="bots.bot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_balances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("bot", "user")},
            },
        ),
        migrations.CreateModel(
            name="BotSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_long", models.BooleanField(default=False)),
                ("status", models.CharField(default="Pending", max_length=10)),
                (
                    "quantity",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
                ),
                (
                    "entry_price",
                    models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
                ),
                (
                    "exit_price",
                    models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("pnl", models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ("roi", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="assets.assetcryptocoin",
                    ),
                ),
                (
                    "balance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="bots.botbalance",
                    ),
                ),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="bots.bot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot Signal",
                "verbose_name_plural": "Bot Signals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BotStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("pnl", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("roi", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="bots.bot",
                    ),
                ),
            ],
            options={
                "db_table": "bot_stats",
            },
        ),
        migrations.CreateModel(
            name="MacdIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "intervals",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("1MIN", "1 minute"),
                                ("5MIN", "5 minutes"),
                                ("15MIN", "15 minutes"),
                                ("30MIN", "30 minutes"),
                                ("1HRS", "1 hour"),
                                ("1DAY", "1 day"),
                            ],
                            max_length=10,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("fast_period", models.IntegerField(default=12)),
                ("slow_period", models.IntegerField(default=26)),
                ("signal_period", models.IntegerField(default=9)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="macd_indicators",
                        to="bots.bot",
                    ),
                ),
            ],
            options={
                "verbose_name": "MACD Indicator",
                "verbose_name_plural": "MACD Indicators",
            },
        ),
        migrations.CreateModel(
            name="MacdValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.DecimalField(decimal_places=10, max_digits=20)),
                ("signal", models.DecimalField(decimal_places=10, max_digits=20)),
                ("histogram", models.DecimalField(decimal_places=10, max_digits=20)),
                (
                    "indicator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="macd_values",
                        to="bots.macdindicator",
                    ),
                ),
                (
                    "quote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="assets.histquotes"
                    ),
                ),
            ],
            options={
                "verbose_name": "MACD Value",
                "verbose_name_plural": "MACD Values",
                "ordering": ["quote__time"],
            },
        ),
        migrations.CreateModel(
            name="MainBotSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("max_signals", models.IntegerField(default=50)),
                ("signals_left", models.IntegerField(default=50)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_user_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bot_settings",
            },
        ),
        migrations.CreateModel(
            name="MaIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "intervals",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("1MIN", "1 minute"),
                                ("5MIN", "5 minutes"),
                                ("15MIN", "15 minutes"),
                                ("30MIN", "30 minutes"),
                                ("1HRS", "1 hour"),
                                ("1DAY", "1 day"),
                            ],
                            max_length=10,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("period", models.IntegerField(default=20)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ma_indicators",
                        to="bots.bot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Moving Average Indicator",
                "verbose_name_plural": "Moving Average Indicators",
            },
        ),
        migrations.CreateModel(
            name="MaValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.DecimalField(decimal_places=10, max_digits=20)),
                (
                    "indicator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ma_values",
                        to="bots.maindicator",
                    ),
                ),
                (
                    "quote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="assets.histquotes"
                    ),
                ),
            ],
            options={
                "verbose_name": "MA Value",
                "verbose_name_plural": "MA Values",
                "ordering": ["quote__time"],
            },
        ),
        migrations.CreateModel(
            name="ObvIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "intervals",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("1MIN", "1 minute"),
                                ("5MIN", "5 minutes"),
                                ("15MIN", "15 minutes"),
                                ("30MIN", "30 minutes"),
                                ("1HRS", "1 hour"),
                                ("1DAY", "1 day"),
                            ],
                            max_length=10,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="obv_indicators",
                        to="bots.bot",
                    ),
                ),
            ],
            options={
                "verbose_name": "OBV Indicator",
                "verbose_name_plural": "OBV Indicators",
            },
        ),
        migrations.CreateModel(
            name="ObvValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.DecimalField(decimal_places=10, max_digits=20)),
                (
                    "indicator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="obv_values",
                        to="bots.obvindicator",
                    ),
                ),
                (
                    "quote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="assets.histquotes"
                    ),
                ),
            ],
            options={
                "verbose_name": "OBV Value",
                "verbose_name_plural": "OBV Values",
                "ordering": ["quote__time"],
            },
        ),
        migrations.CreateModel(
            name="RsiIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "intervals",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("1MIN", "1 minute"),
                                ("5MIN", "5 minutes"),
                                ("15MIN", "15 minutes"),
                                ("30MIN", "30 minutes"),
                                ("1HRS", "1 hour"),
                                ("1DAY", "1 day"),
                            ],
                            max_length=10,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("min", models.IntegerField(default=30)),
                ("max", models.IntegerField(default=70)),
                ("period", models.IntegerField(default=14)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsi_indicators",
                        to="bots.bot",
                    ),
                ),
            ],
            options={
                "verbose_name": "RSI Indicator",
                "verbose_name_plural": "RSI Indicators",
            },
        ),
        migrations.CreateModel(
            name="RsiValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.DecimalField(decimal_places=10, max_digits=20)),
                (
                    "indicator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rsi_values",
                        to="bots.rsiindicator",
                    ),
                ),
                (
                    "quote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="assets.histquotes"
                    ),
                ),
            ],
            options={
                "verbose_name": "RSI Value",
                "verbose_name_plural": "RSI Values",
            },
        ),
        migrations.CreateModel(
            name="SupportResistanceIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "intervals",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("1MIN", "1 minute"),
                                ("5MIN", "5 minutes"),
                                ("15MIN", "15 minutes"),
                                ("30MIN", "30 minutes"),
                                ("1HRS", "1 hour"),
                                ("1DAY", "1 day"),
                            ],
                            max_length=10,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("rolling", "Rolling High/Low"),
                            ("pivots", "Pivot Points"),
                            ("both", "Rolling + Pivots"),
                        ],
                        default="both",
                        max_length=10,
                    ),
                ),
                (
                    "lookback",
                    models.PositiveIntegerField(
                        default=50, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "levels_count",
                    models.PositiveIntegerField(
                        default=6,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "zone_mode",
                    models.CharField(
                        choices=[("atr", "ATR-based"), ("fixed", "Fixed percent of price")],
                        default="atr",
                        max_length=5,
                    ),
                ),
                (
                    "atr_period",
                    models.PositiveIntegerField(
                        default=14, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "atr_mult",
                    models.FloatField(
                        default=0.75, validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "fixed_width",
                    models.FloatField(
                        default=0.002,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(0.5),
                        ],
                    ),
                ),
                (
                    "merge_dist_atr",
                    models.FloatField(
                        default=0.5, validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "pivot_type",
                    models.CharField(
                        choices=[
                            ("classic", "Classic"),
                            ("fibo", "Fibonacci"),
                            ("woodie", "Woodie"),
                            ("camarilla", "Camarilla"),
                        ],
                        default="classic",
                        max_length=10,
                    ),
                ),
                (
                    "pivot_tf",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly")],
                        default="daily",
                        max_length=7,
                    ),
                ),
                ("vwap_enabled", models.BooleanField(default=True)),
                (
                    "vwap_bands",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sr_indicators",
                        to="bots.bot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Support/Resistance Indicator",
                "verbose_name_plural": "Support/Resistance Indicators",
            },
        ),
        migrations.CreateModel(
            name="UserBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_balance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
