# Generated by Django 5.2.1 on 2026-05-25 17:45

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_quote_unique_together_remove_quote_symbol_and_more'),
        ('bots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmaIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervals', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('1MIN', '1 minute'), ('5MIN', '5 minutes'), ('15MIN', '15 minutes'), ('30MIN', '30 minutes'), ('1HRS', '1 hour'), ('1DAY', '1 day')], max_length=10), blank=True, default=list, size=None)),
                ('period', models.IntegerField(default=14)),
            ],
            options={
                'verbose_name': 'EMA Indicator',
                'verbose_name_plural': 'EMA Indicators',
            },
        ),
        migrations.CreateModel(
            name='FiboIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervals', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('1MIN', '1 minute'), ('5MIN', '5 minutes'), ('15MIN', '15 minutes'), ('30MIN', '30 minutes'), ('1HRS', '1 hour'), ('1DAY', '1 day')], max_length=10), blank=True, default=list, size=None)),
                ('period', models.IntegerField(default=50)),
                ('levels', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), default=list, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('funding_time', models.BigIntegerField()),
                ('exchange', models.CharField(max_length=100)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets_funding', to='assets.assetcryptocoin')),
            ],
            options={
                'unique_together': {('asset', 'exchange')},
            },
        ),
        migrations.CreateModel(
            name='RiskSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risk Settings',
                'verbose_name_plural': 'Risk Settings',
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('is_long', models.BooleanField(default=True)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_asset', to='assets.assetcryptocoin')),
            ],
            options={
                'verbose_name': 'Signal',
                'verbose_name_plural': 'Signals',
                'db_table': 'signal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='atrvalue',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='atrvalue',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='bollingerbandsvalue',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='bollingerbandsvalue',
            name='quote',
        ),
        migrations.AlterUniqueTogether(
            name='botbalance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='botbalance',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='botbalance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='botsignal',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='botsignal',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='botsignal',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='botstat',
            name='bot',
        ),
        migrations.DeleteModel(
            name='FnGValue',
        ),
        migrations.RemoveField(
            model_name='macdvalue',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='macdvalue',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='mainbotsettings',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mavalue',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='mavalue',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='obvvalue',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='obvvalue',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='rsivalue',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='rsivalue',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='userbalance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='intersection',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='last_heartbeat',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='max_drawdown',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='risk',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='runtime',
        ),
        migrations.AlterModelTable(
            name='bot',
            table=None,
        ),
        migrations.AddField(
            model_name='emaindicator',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ema_indicators', to='bots.bot'),
        ),
        migrations.AddField(
            model_name='fiboindicator',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fibo_indicators', to='bots.bot'),
        ),
        migrations.AddField(
            model_name='signal',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_signals', to='bots.bot'),
        ),
        migrations.DeleteModel(
            name='AtrValue',
        ),
        migrations.DeleteModel(
            name='BollingerBandsValue',
        ),
        migrations.DeleteModel(
            name='BotBalance',
        ),
        migrations.DeleteModel(
            name='BotSignal',
        ),
        migrations.DeleteModel(
            name='BotStat',
        ),
        migrations.DeleteModel(
            name='MacdValue',
        ),
        migrations.DeleteModel(
            name='MainBotSettings',
        ),
        migrations.DeleteModel(
            name='MaValue',
        ),
        migrations.DeleteModel(
            name='ObvValue',
        ),
        migrations.DeleteModel(
            name='RsiValue',
        ),
        migrations.DeleteModel(
            name='UserBalance',
        ),
        migrations.AddConstraint(
            model_name='signal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_open', True)), fields=('bot', 'asset'), name='unique_open_signal_per_bot_asset'),
        ),
    ]
