from django.urls import path

from . import views

urlpatterns = [
    path("register/start/", views.RegisterStartView.as_view(),
         name="register"),
    path("register/verify/",
         views.RegisterVerifyView.as_view(),
         name="register-verify"),
    path("register/resend/",
         views.RegisterResendView.as_view(),
         name="register-resend"),
    path("register/",
         views.RegisterView.as_view(),
         name="register"),
    path("login/",
         views.LoginView.as_view(),
         name="login"),
    path("refresh/",
         views.RefreshTokenView.as_view(),
         name="token_refresh"),
    path("checkout/",
         views.create_checkout_session),
    path("portal/",
         views.create_billing_portal_session),
    path("webhook/",
         views.stripe_webhook),
    path("reset/start/",
         views.ResetStartView.as_view(),
         name="reset-start"),
    path("reset/verify/",
         views.ResetVerifyView.as_view(),
         name="reset-verify"),
    path("get_user_tg/",
         views.GetUserTelegram.as_view(),
         name="get_user_tg"),
    path(
        "billing/create-checkout-session/",
        views.create_checkout_session,
        name="create_checkout_session",
    ),
    path(
        "billing/portal/", 
        views.create_billing_portal_session,
        name="create_billing_portal_session"
    ),
    path("billing/me/",
         views.billing_me,
         name="billing_me"),
    path(
        "add_telegram/",
        views.AddTelegram.as_view(),
        name="add_telegram",
    ),
    path("me/",
         views.me,
         name="me"),
    path(
        "get_tg_info/",
        views.GetTelegramInfo.as_view(),
        name="add_telegram",
    ),
]
